# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{swiss_tournament}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Peter Westman"]
  s.date = %q{2011-07-15}
  s.description = %q{Plugin to be used in a rails application that manages swiss tournaments.}
  s.email = %q{westman.peter@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Rakefile",
    "VERSION",
    "features/step_definitions/tournament_steps.rb",
    "features/support/env.rb",
    "features/support/required_test_files.rb",
    "features/tournament.feature",
    "init.rb",
    "lib/swiss.rb",
    "lib/swiss_tournament.rb",
    "lib/swiss_tournament/acts_as_match.rb",
    "lib/swiss_tournament/acts_as_participation.rb",
    "lib/swiss_tournament/acts_as_player.rb",
    "lib/swiss_tournament/acts_as_tournament.rb",
    "lib/swiss_tournament/tournament_round.rb",
    "lib/swiss_tournament/tournament_round_creator.rb",
    "rails/init.rb",
    "spec/factories.rb",
    "spec/include/match.rb",
    "spec/include/participation.rb",
    "spec/include/player.rb",
    "spec/include/schema.rb",
    "spec/include/tournament.rb",
    "spec/models/match_spec.rb",
    "spec/models/participation_spec.rb",
    "spec/models/tournament_round_creator_spec.rb",
    "spec/models/tournament_round_spec.rb",
    "spec/models/tournament_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/elchtzeasar/swiss_tournament}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Swiss tournament plugin for a Rails application}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.0.0"])
      s.add_development_dependency(%q<rspec>, [">= 2.6.0"])
      s.add_development_dependency(%q<cucumber>, [">= 1.0.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
    else
      s.add_dependency(%q<rails>, [">= 3.0.0"])
      s.add_dependency(%q<rspec>, [">= 2.6.0"])
      s.add_dependency(%q<cucumber>, [">= 1.0.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.0.0"])
    s.add_dependency(%q<rspec>, [">= 2.6.0"])
    s.add_dependency(%q<cucumber>, [">= 1.0.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
  end
end

